name: github-actions-testing
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: '12.x'
    - name: Install dependencies
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test