name: github-actions-testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      strategy:
        matrix:
          node: ['20.x', '14.x', '12.x']
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm init -y && npm install --save-dev jest && npm ci
    - name: Build the project
      run: npm run build --if-present
    - name: Run tests
      run: npx jest