name: github-actions-testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm init -y && npm ci
    - name: Build the project
      run: npm run build --if-present
    - name: Run tests
      run: npm test